"""
Django settings for ALL project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==================== 安全配置 ====================
# SECURITY WARNING: keep the secret key used in production secret!
# 从环境变量读取密钥，如果没有则使用默认值（仅用于开发）
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure--%saas=diln%m0ozg2grw$&**u-puw(6@y#m&fa^g_yfah4#50')

# SECURITY WARNING: don't run with debug turned on in production!
# 从环境变量读取调试模式，默认为True（开发环境）
# 生产环境请设置环境变量 DJANGO_DEBUG=False
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

# 允许的主机列表
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'konachan.apps.KonachanConfig',
    'wallhaven.apps.WallhavenConfig',
    'hls.apps.HlsConfig',
    'fs.apps.FsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ==================== CORS配置 ====================
# CORS设置，允许局域网访问
# 注意：生产环境应该限制允许的源
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'True').lower() in ('true', '1', 'yes')
CORS_ALLOW_CREDENTIALS = os.getenv('CORS_ALLOW_CREDENTIALS', 'True').lower() in ('true', '1', 'yes')

ROOT_URLCONF = 'ALL.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ALL.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# 静态文件收集目录（用于生产环境）
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 静态文件目录配置
STATICFILES_DIRS = [
    BASE_DIR / 'konachan' / 'static',
    BASE_DIR / 'wallhaven' / 'static',
    BASE_DIR / 'fs' / 'static',
]

# Media files (User uploaded files)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'Media'  # 其他应用使用Media/目录

# FS模块专用媒体目录（小写media）
FS_MEDIA_ROOT = BASE_DIR / 'media'  # fs模块使用media/目录

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration
# https://docs.djangoproject.com/en/5.2/topics/logging/

# 创建日志目录（如果不存在）
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

# ==================== 日志配置 ====================
# 日志级别（从环境变量读取，默认为INFO）
LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO').upper()

# 日志配置
LOGGING = {
    # 版本
    'version': 1,
    # 禁用其他日志记录器
    'disable_existing_loggers': False,
    # 格式化器
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    # 处理器
    'handlers': {
        # 应用日志记录器
        'file': {
            'level': LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'app.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB（修正：之前写的是100MB）
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Konachan日志记录器
        'klog_file': {
            'level': LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'KLog.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # HLS日志记录器
        'hls_file': {
            'level': LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'hls.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Wallhaven日志记录器
        'wallhaven_file': {
            'level': LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'wallhaven.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # 控制台日志记录器
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },

    # 根日志记录器
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    
    # 日志记录器
    'loggers': {
        'konachan': {
            'handlers': ['klog_file', 'console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'hls': {
            'handlers': ['hls_file', 'console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'wallhaven': {
            'handlers': ['wallhaven_file', 'console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django': {
            'handlers': ['file', 'console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}